### PR TITLE
Create a vault for carbon protocol v3

### LINKED ISSUE #2: Create a vault for carbon protocol v3
**Description**
Create a sc vault that batch fetch data for carbon protocol v3. Lower the frequency of fetch in the blockchain.

---
**Acceptance Criteria**
---

- [ ] Make a batch  getter :
    - That takes an array of addresses for every project
    - get all owners with their balance,  for each vintage balance , their status

**Additional context**
---
[ Easy - Cairo / Backend]

### PR DESCRIPTION
**Pull request by manlikeHB**
closes #2

### CODE REVIEW

**Comment by manlikeHB** [comment]
Hi @LouGel, PR ready for review.

**Review by LouGel — CHANGES_REQUESTED** [review]
Hi , since  there will be  multiple project contract we want a bit more modularity. we can push an array of project address with the user address. to get an overall projectS balance per user. at each vintage.  MWhat you've done is good. Just need a side function that takes the  array of project address. And remove the project in the constructor since projectS addresses will be in the function.

**Review by LouGel — CHANGES_REQUESTED** [review]
Nice !
Just need 2 things:

-Vault files have to be at src (in the file where there is the todo) ,not in the cpv3 dir, as well as the test.  Not in the cp-v3.
- Can you just rename  batch_getter ->  get_batch_users_info_for_project and get_all_user_carbon_info -> get_batch_project_info_for_user
-

**Review by LouGel — APPROVED** [review]
LGTM ! Welle done

**Pull request merged**
